var blogPosts = [
{Title: "<article class='articleBlog'><header class='headerBlog'><h2>NSS Bootcamp Week #2</h2></header>", Copy: "<section class='sectionBlog'><p>We really started hitting Javascript this week. I struggled with it some, primarily because I hadn't caught up on the exercises. But Thursday evening I decided to really hit the Javascript exercises hard and I'm feeling more confident this morning. I was able to figure out the Javascript for the group project, which makes me feel like I'm really starting to get the hang of it. More practice is definitely needed, but I'm feeling more solid now.</p><p>The second half of this week also featured our first group projects, and then first group project part two. We had to do it twice. It was a website for a fake client where we populated the products page using Javascript. I was initially group lead and my first group project came together really well, and with Madeline as the styling expert it really looked beautiful. Our biggest challenge was (surprise), the Javascript. Our Javascript functioned, but it didn't loop and wasn't DRY. I had been thinking to myself if I were to do it again that I'd start with the Javascript. I guess this was fortunate because the cohort struggled enough that they decided we needed to do it again, so I got a chance to do it. Project One Part Two features much more beautiful Javascript and less beautiful styling (Madeline is not in my second group), so we're getting six of one half a dozen of another.</p><p class='lastParagraph'>I was able to finish all of the exercises for the first milestone. I'm pleased because I lowkey want to be the first person to finish all the exercises.</p></section>", Date: "<footer class='footerBlog'><h4>Eliza W Meeks</h4><p>April 14, 2017</p></footer></article>"},
{Title: "<article class='articleBlog'><header class='headerBlog'><h2>NSS Bootcamp Week #1</h2></header>", Copy: "<section class='sectionBlog'><p>Thus began the journey at Nashville Software school: an orientation day, followed immediately by the presentation of the capstone projects of Cohort 18 (the cohort immediately preceding ours), then intro to HTML, CSS, and JavaScript.</p><p>So far the HTML, CSS, and Javascript that has been covered is all right from the pre work, so I'm feeling fairly confident about it. Doing the exercises has proved validating in terms of proving that I know this stuff and can do it with relative ease. Using the terminal was a little surprising the first day--I hadn't gotten that far in the prework--but I seem to have gotten the hang of it. It's really cool to see past the GUI and into what's actually going on in the computer.</p><p>One of the aspects that I had been totally unfamiliar with is using git and gitHub, but I think I'm getting the hang of the one-way street and the process. After we had downloaded git, Twitter Friend Smingleigh told me to never use git push master force. I joked about using git push master jedi, but now a few days later I actually understand what git push master force is and why I shouldn't use it.</p><p>Cohort 18 presented the capstone projects from their first three months, giving us an idea of what we might be able to make at the end of twelve weeks. It's gotten me brainstorming what app I want to make. I came up with a couple of ideas: an app that curates color palettes using hex code and common HTML names for easy color palettes that you don't have to use a color picker to find the colors. I'm particularly interested in the idea of doing it with color names to increase accessibility for color blind individuals.</p><p class='lastParagraph'>The other idea I came up with (which is, frankly, what I'm more likely to do) is an app for tracking FPIES triggers, reactions, and all of the other fun things concomitant with FPIES. I'm thinking of making an app where you can login, and create profiles for each child with FPIES. You can then make a list of triggers, a list of safe foods, track trials, reactions, or any medical information or ER notes. I think it could be useful in keeping track of everything you might need to track with FPIES. The goal would ultimately be a mobile app. I need to make a Trello to start listing ideas. I figure if I've got an eye on what I want to make, I can keep track of the types of coding and procedures I need to use to make it happen.</p></section>", Date: "<footer class='footerBlog'><h4>Eliza W Meeks</h4><p>April 7, 2017</p></footer></article>"}];


// Looping through Array:

var txt = "";
var x;

for (x in blogPosts){
	txt += blogPosts[x].Title + blogPosts[x].Copy + blogPosts[x].Date;
}

document.getElementById("blog").innerHTML = "<h5>Blog</h5>" + txt;